### ISSUE TITLE
 LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored

### ISSUE THREAD

**Issue by zssjh** [yuxng/DA-RNN#15]
zss@zss:~/DA-RNN$ ./experiments/scripts/rgbd_scene_multi_*.sh $GPU_ID
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=./experiments/scripts/rgbd_scene_multi_depth.sh
+ CUDA_VISIBLE_DEVICES=./experiments/scripts/rgbd_scene_multi_depth.sh
+ export LD_PRELOAD=/usr/lib/libtcmalloc.so.4
+ LD_PRELOAD=/usr/lib/libtcmalloc.so.4
++ date +%Y-%m-%d_%H-%M-%S
ERROR: ld.so: object '/usr/lib/libtcmalloc.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
+ LOG=experiments/logs/rgbd_scene_multi_color.txt.2018-01-11_19-51-45
+ exec
++ tee -a experiments/logs/rgbd_scene_multi_color.txt.2018-01-11_19-51-45
ERROR: ld.so: object '/usr/lib/libtcmalloc.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
+ echo Logging output to experiments/logs/rgbd_scene_multi_color.txt.2018-01-11_19-51-45
Logging output to experiments/logs/rgbd_scene_multi_color.txt.2018-01-11_19-51-45
+ ./tools/train_net.py --gpu 0 --network vgg16 --weights data/imagenet_models/vgg16_convs.npy --imdb rgbd_scene_train --cfg experiments/cfgs/rgbd_scene_multi_color.yml --iters 40000
ERROR: ld.so: object '/usr/lib/libtcmalloc.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/libtcmalloc.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Traceback (most recent call last):
  File "./tools/train_net.py", line 13, in <module>
    from fcn.train import get_training_roidb, train_net
  File "/home/zss/DA-RNN/tools/../lib/fcn/train.py", line 11, in <module>
    from gt_data_layer.layer import GtDataLayer
  File "/home/zss/DA-RNN/tools/../lib/gt_data_layer/layer.py", line 12, in <module>
    from gt_data_layer.minibatch import get_minibatch
  File "/home/zss/DA-RNN/tools/../lib/gt_data_layer/minibatch.py", line 17, in <module>
    import scipy.io
ImportError: No module named scipy.io
Could anyone help me about the problem ?
Thank you very much!

**Comment by yuxng** [comment]
sudo apt-get install google-perftools
