### ISSUE TITLE
undefined symbol: _ZN2df12KinectFusionC1ESs on trained model test script

### ISSUE THREAD

**Issue by Wei2624** [yuxng/DA-RNN#20]
Dear Dr. Xiang @yuxng ,

Thanks for the work. I am working on reproducing your code on my docker image. 

Everything is compiled. I can run the test script without kfusion set to True. However, once set it to True, I got the error as follows:

```
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/rgbd_scene_multi_rgbd_test.txt.2018-06-14_23-27-31
+ exec
++ tee -a experiments/logs/rgbd_scene_multi_rgbd_test.txt.2018-06-14_23-27-31
+ echo Logging output to experiments/logs/rgbd_scene_multi_rgbd_test.txt.2018-06-14_23-27-31
Logging output to experiments/logs/rgbd_scene_multi_rgbd_test.txt.2018-06-14_23-27-31
+ '[' -f /home/weizhang/DA-RNN/output/rgbd_scene/rgbd_scene_val/vgg16_fcn_rgbd_multi_frame_rgbd_scene_iter_40000/segmentations.pkl ']'
+ ./tools/test_net.py --gpu 0 --network vgg16 --model data/fcn_models/rgbd_scene/vgg16_fcn_rgbd_multi_frame_rgbd_scene_iter_40000.ckpt --imdb rgbd_scene_val --cfg experiments/cfgs/rgbd_scene_multi_rgbd.yml --rig data/RGBDScene/camera.json --kfusion 1
Traceback (most recent call last):
  File "./tools/test_net.py", line 13, in <module>
    from fcn.test import test_net
  File "/home/weizhang/DA-RNN/tools/../lib/fcn/test.py", line 25, in <module>
    from kinect_fusion import kfusion
ImportError: /home/weizhang/DA-RNN/tools/../lib/kinect_fusion/kfusion.so: undefined symbol: _ZN2df12KinectFusionC1ESs

```

I am not sure if this is caused by compiling kinect fusion improperly. And comments are very appreciated. 

And also @kevinkit , did you successfully run the script with kfusion to 1 in a docker?

Thanks for the help!.

**Comment by rockkingjy** [comment]
I get the same error, any solution? @Wei2624 @yuxng

**Comment by Wei2624** [comment]
@rockkingjy I work it around by adding `add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)` to CMakeList.txt in KniectFusion. You can try it.
